In [1]:
import numpy as np
x=np.random.random((5,3))
print("FIRST ARRAY:")
print(x)
import numpy as np
y=np.random.random((3,2))
print("SECOND ARRAY:")
print(y)
print("Dot Product of Two Array is:")
z = np.dot(x,y)
print(z)

FIRST ARRAY:
[[0.34491388 0.15108265 0.68885536]
 [0.78163519 0.72188429 0.200316  ]
 [0.85923351 0.9763561  0.90770599]
 [0.23352917 0.6397436  0.71567468]
 [0.25090559 0.21829775 0.72328852]]
SECOND ARRAY:
[[0.98441562 0.25242537]
 [0.20566965 0.16469078]
 [0.66613816 0.84118736]]
Dot Product of Two Array is:
[[0.82948457 0.69140335]
 [1.05136172 0.48469552]
 [1.65130731 1.14123999]
 [0.83820382 0.76632505]
 [0.77370269 0.70770772]]


In [2]:
import numpy as np
print('\n Origional Array :\n')
array=['Python','PHP','JS','Examples','html5','5']
print(array)
print('\n IS DIGIT CASES ONLY IN Array :\n')
for x in array:
       print(x.isdigit(), end=",")
print('\n IS LOWER CASES ONLY IN Array :\n')
for x in array:
       print(x.islower(), end=",")
print('\n IS UPPER CASES ONLY IN Array :\n')
for x in array:
       print(x.isupper(), end=",")


 Origional Array :

['Python', 'PHP', 'JS', 'Examples', 'html5', '5']

 IS DIGIT CASES ONLY IN Array :

False,False,False,False,False,True,
 IS LOWER CASES ONLY IN Array :

False,False,False,False,True,False,
 IS UPPER CASES ONLY IN Array :

False,True,True,False,False,False,

In [3]:
import numpy as np
X=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]).reshape(4,4)
Y=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]).reshape(4,4)
np3=np.subtract(X,Y)
print("\n Origional Array is:\n")
print(np3)

np3=np.reshape(np3,16)
print("\n Modified array is\n")
print(np3)


 Origional Array is:

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

 Modified array is

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [4]:
import numpy as np
import pandas as pd
P=np.array([23,56,87,3,6,96,4,6,78]).reshape(3,3)
print(P)
Q=np.array([12,34,54,7,2,54,6,2,78]).reshape(3,3)
print(Q)
print(P-Q)


[[23 56 87]
 [ 3  6 96]
 [ 4  6 78]]
[[12 34 54]
 [ 7  2 54]
 [ 6  2 78]]
[[11 22 33]
 [-4  4 42]
 [-2  4  0]]
